version: '2'
services:
    cassandra1:
        container_name: cassandra1-container
        image: cassandra:3.3
        # volumes:
        #     - ~/volumes/jhipster/jhipsterCassandraSampleApplication/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    master:
      image: gettyimages/spark:1.5.2-hadoop-2.6
      command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
      hostname: master
      environment:
        SPARK_CONF_DIR: /conf
        MASTER: spark://master:7077
      links:
        - cassandra1
        - hadoop-namenode:hdfs-namenode
        - hadoop-datanode1:hdfs-datanode1
      expose:
        - 7001-7006
        - 7077
        - 6066
      ports:
        - 4040:4040
        - 6066:6066
        - 7077:7077
        - 8080:8080
      volumes:
        - ./spark/conf/master:/conf
        - ./spark/data:/tmp/data
        - ./hadoop/conf:/etc/hadoop

    worker:
      image: gettyimages/spark:1.5.2-hadoop-2.6
      command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
      hostname: worker
      environment:
        SPARK_CONF_DIR: /conf
        SPARK_WORKER_CORES: 2
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8881
        SPARK_WORKER_WEBUI_PORT: 8081
      links:
        - master
        - cassandra1
        - hadoop-namenode:hdfs-namenode
        - hadoop-datanode1:hdfs-datanode1
      expose:
        - 7001-7006
        - 8881
      ports:
        - 8081:8081
      volumes:
        - ./spark/conf/worker:/conf
        - ./spark/data:/tmp/data
        - ./hadoop/conf:/etc/hadoop

    hadoop-namenode:
      image: gelog/hadoop:2.6.0
      command: hdfs namenode
      hostname: hdfs-namenode
      ports:
       - 50070:50070
      volumes:
       - ./hadoop/name:/data/dfs/name

    hadoop-datanode1:
      image: gelog/hadoop:2.6.0
      command: hdfs datanode 
      hostname: hdfs-datanode1
      links:
       - hadoop-namenode:hdfs-namenode
      ports:
       - 50075:50075

    hadoop-secondarynamenode:
      image: gelog/hadoop:2.6.0
      command: hdfs secondarynamenode
      hostname: hdfs-secondarynamenode
      links:
       - hadoop-namenode:hdfs-namenode
      ports:
       - 50090:50090


    app:
      image: gettyimages/spark:1.5.2-hadoop-2.6
      command: /bin/bash
      hostname: app
      environment:
        SPARK_CONF_DIR: /conf
      links:
        - master
        - worker
        - cassandra1
        - hadoop-namenode:hdfs-namenode
        - hadoop-datanode1:hdfs-datanode1

      expose:
        - 7001-7006
      volumes:
        - ./spark/conf/app:/conf
        - ./spark/data:/tmp/data
        - ./files-importer:/files-importer
        - ./hadoop/conf:/etc/hadoop

